name: Python Run - every 4 hours run a script and then commit to GitHub repo

on:
  schedule:
  - cron: '0 */4 * * *' # Run every 4 hours, every day

  workflow_dispatch:

# Grant write permissions for all jobs in this workflow
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 # Action to clone the repo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ matrix.python-version }} # Specify the Python version
      - name: Cache pip packages
        id: pip-cache
        uses: actions/cache@v5
        with:
        # Cache key includes OS, Python version, and a hash of the lock file
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        # Restore from any previous cache with the same OS and Python version
          restore-keys: |
            ${{ runner.os }}-pip-
        # Directories to cache (default pip cache location)
          path: |
            ~/.cache/pip
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run create_list_v2.py
        run: python create_list_v2.py
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Updated using Python script using a GitHub Action"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# OLD
# python -m pip install --upgrade pip